# Database
spring:
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
               dialect: org.hibernate.dialect.MySQL5Dialect 
spring:
    datasource:
        url: jdbc:mysql://localhost/springblog?useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 1234
        platform: mysql
        
        
# Resource handling

spring:
    resources:
        add-mappings: true
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
        
        
# Embedded server configuration

server:
    compression:
        enabled: true
        min-response-size: 2048