# Database
spring:
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
               dialect: org.hibernate.dialect.MySQL5Dialect 
spring:
    datasource:
        url: jdbc:mysql://localhost/springblog?useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 1234
        platform: mysql