# Database

spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
               dialect: org.hibernate.dialect.H2Dialect
spring:
    datasource:
        url: jdbc:h2:mem:springblog
        driver-class-name: org.h2.Driver
        username: sa
        password:
spring:
    h2:
        console:
            enabled: true
            path: /dbconsole
            